### ISSUE TITLE
 Visual Studio 2015 RC ?

### ISSUE THREAD

**Issue by haar03** [abelectronicsuk/ABElectronics_Win10IOT_Libraries#1]
i can not open this project in the current verion of VS 2015. (Update needed) link bings me to the MS page. https://msdn.microsoft.com/en-us/windows/uwp/porting/update-your-visual-studio-2015-rc-project-to-rtm. I just need  a compiled .dll is there a work around?

**Comment by abelectronicsuk** [comment]
I have updated the project files and code to work with the latest version of Visual Studio 2015.  The compiled .dll for the library can be found in \ABElectronics_Win10IOT_Libraries\bin\ARM\Release
