### ISSUE TITLE
You should create a Nuget package.

### ISSUE THREAD

**Issue by carldebilly** [abelectronicsuk/ABElectronics_Win10IOT_Libraries#3]
If you don't know how to do this, I can help you doing this.

**Comment by abelectronicsuk** [comment]
I have added the library onto Nuget, that you for the suggestion and all of the changes you made to improve the library.  It should be available to download from [https://www.nuget.org/packages/ABElectronics_Win10IOT_Libraries/](https://www.nuget.org/packages/ABElectronics_Win10IOT_Libraries/) once they have indexed the package.
