### ISSUE TITLE
DLL missing from the NuGet package

### ISSUE THREAD

**Issue by jessenic** [abelectronicsuk/ABElectronics_Win10IOT_Libraries#7]
The latest NuGet package (1.2.6866.16968) does not have the actual library DLL inside. Updating to it breaks the build.

**Comment by abelectronicsuk** [comment]
Sorry for the error.  I have uploaded a new version to NuGet that should have the DLL file inside.  You can download it directly using "Install-Package ABElectronics_Win10IOT_Libraries -Version 1.2.6890.29475"
